### PR TITLE
Add more flags

### PR DESCRIPTION
**Pull request by 0xf0xx0**
came across this while browsing r/unixporn, have some flags uwu

### CODE REVIEW

**Comment by flyingcakes85** [comment]
Did your formatter change the whole file to have 4 spaces instead of 2? >_<

**Comment by angelofallars** [comment]
@ExperiBass can you change the indentation to be two spaces instead of four?

**Comment by 0xf0xx0** [comment]
Will do, sorry bout that

**Comment by 0xf0xx0** [comment]
done!

**Comment by angelofallars** [comment]
@ExperiBass Thanks! Looks good to me!

**Pull request merged**
